### PR TITLE
Use local jQuery source

### LINKED ISSUE #1: Bundle jQuery instead of using CDN
There are a couple of things from [the proposal](https://github.com/readthedocs/readthedocs.org/pull/9665) that aren't implemented.

But I wanted to flag the usage of a CDN jQuery since it's currently implemented in a way that conflicts with the proposal.

### PR DESCRIPTION
**Pull request by AA-Turner**
- Vendor jQuery within the extension
- Include the Sphinx compatability file
- Update tests

Closes #1 

A

### CODE REVIEW

**Review by benjaoming — CHANGES_REQUESTED** [review]
Nice! Shouldn't jQuery be minified? The original one was: https://github.com/sphinx-doc/sphinx/blob/v5.3.0/sphinx/themes/basic/static/jquery.js

**Comment by benjaoming** [comment]
Really awesome, fast work :100: :rocket:

**Comment by AA-Turner** [comment]
https://github.com/sphinx-contrib/jquery/blob/include-as-files/sphinxcontrib/jquery/jquery.js

The file with the version prefix isn't minified, I copied it over anyway though.

A

**Comment by benjaoming** [comment]
Right, now I see!

Maybe worth naming the actively included file as `jquery-3.6.0.min.js` because it should be aggressively cached? Hence, if the extension is upgraded with a new version of `jquery.js`, won't that be cached as well?

I'm not sure why the unminified version needs to be included. For verification, the official minified version should suffice.

In the future, if we want to provide an easy debugging mechanism, we could do that... but it's not currently possible to switch on the un-minified version, anyways?

**Comment by benjaoming** [comment]
I'm requesting something that didn't happen in Sphinx, so it's a scope creep.. you can disregard :+1:

**Comment by AA-Turner** [comment]
I'll merge as-is for parity with Sphinx, we can make improvements (e.g. file renames) in subsequent PRs.

A

**Pull request merged**
